name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.11.0

      - name: Install dependencies and build
        run: npm i && npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./dist
          branch: gh-pages
